<?php
$PASSWORD_DOESNT_MATCH = "PASSWORD_DOESNT_MATCH";
$USERNAME_CONTAINS_WHITESPACE = "USERNAME_CONTAINS_WHITESPACE";
$USERNAME_ALREADY_TAKEN = "USERNAME_ALREADY_TAKEN";
$USER_NOT_FOUND = "USER_NOT_FOUND";
$WRONG_PASSWORD = "WRONG_PASSWORD";
$SUCCESS = "SUCCESS";
?>